### ISSUE TITLE
fatal error: Status code is 500..

### ISSUE THREAD

**Issue by someonewhoplayvhack** [MrSonicMaster/vHackXT-MoneyBot#6] opened 2017-03-05 14:35 UTC
Ur bot work very fine but problem. 
![capture](https://cloud.githubusercontent.com/assets/26185813/23588148/69125ffe-01b9-11e7-906d-1813b5963d9e.PNG)

**Comment by MrSonicMaster** [comment] 2017-03-05 16:36
Duplicate of issue #4 .

**Closed as completed by MrSonicMaster** 2017-03-05 16:36 UTC
Labels: duplicate
