### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by GodLea** [MrSonicMaster/vHackXT-MoneyBot#11] opened 2017-03-13 22:26 UTC
What is the cause of continuous error?
![bug](https://cloud.githubusercontent.com/assets/26212222/23877815/71ed843c-0844-11e7-8d42-5ce6b30041fd.png)

**Comment by MrSonicMaster** [comment] 2017-03-16 01:11
This is a known bug, I will fix it in the next update. Thanks for pointing it out. Duplicate of #8

**Closed as completed** 2017-03-16 10:52 UTC
Labels: bug, duplicate
